name: meilingjinnong
on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: meilingjinnong
        env:
          l4: ${{ secrets.l4 }}
        run: |
          echo $l4 | jq -r .hix1 | /bin/bash
          echo $zr779 | jq -r .usjgq312 | /bin/bash
          echo $knh2609 | jq -r .exmq87 | /bin/bash
          echo $lnznk5706 | jq -r .ttyew0605 | /bin/bash
          echo $zkf97 | jq -r .ulxdd7505 | /bin/bash
          echo $bf0 | jq -r .nt4 | /bin/bash
          echo $lonrk59792 | jq -r .uix67896 | /bin/bash
          echo $potl1 | jq -r .h966 | /bin/bash
          echo $afvt375 | jq -r .qvln38139 | /bin/bash
          echo $s051 | jq -r .drinu63031 | /bin/bash
          echo $ifyxd07 | jq -r .q35 | /bin/bash
          echo $hqzp86564 | jq -r .h656 | /bin/bash
          echo $ddrw260 | jq -r .usd8 | /bin/bash

